### ISSUE TITLE
2.0.0 is 1.1.0?

### ISSUE THREAD

**Issue by joesixpack** [Heat-Ledger-Ltd/heatledger#4]
Just installed 2.0.0 server & wallet and now this:

![image](https://user-images.githubusercontent.com/23145642/31443207-a090ec84-ae4d-11e7-8268-c60c932016ee.png)

**Comment by dmdeklerk** [comment]
That message indicates you are not running 2.0.0 **server**.
Did you by any chance copy over or write over two different versions?

We have not received this from anyone which makes me think something went wrong during your installation.
Did you get it working already?

**Comment by joesixpack** [comment]
I installed 2.0.0 over 1.1.0 twice and then deleted the heat_db dir.

I just tried it again and same issue.  Any ideas what to do next?

**Comment by joesixpack** [comment]
In the lib directory of 2.0.0 zip, all the files are dated 4/25/17...

**Comment by dmdeklerk** [comment]
Some libraries are.. yes, not all.
heatledger-2.0.0.jar should be dated 9 okt 2017.
When upgrading best is to backup your blockchain folder and your
heat.properties (if any) only and completely remove all other files/folders.
After you've put all files in place you could manually move your old
blockchain folder to your new installation.

Hope this helps.


2017-10-12 16:14 GMT+02:00 joesixpack <notifications@github.com>:

**Comment by joesixpack** [comment]
That worked, thanks!
