### ISSUE TITLE
HTTP API

### ISSUE THREAD

**Issue by Serg-Maximchuk** [Heat-Ledger-Ltd/heatledger#6]
Where can I find any heatledger HTTP API documentation? I saw https://heatwallet.com/api/ but it is a desktop wallet, should I use this wallet instead of just heatledger on my server?

**Comment by dmdeklerk** [comment]
Hi,

There is only one HTTP API, its docs are here https://heatwallet.com/api/ 
Whether you run the desktop wallet on your PC or just the server without the UI (from the command line) the same API will be used and will be available.

Which wallet you run (desktop or server) is up to you.



As I might offer an alternative. 
Its possible as well to run a desktop wallet in light mode (this means no server runs on your PC, only the UI) and connect that desktop wallet to your own heat server running online somewhere.

**Comment by Serg-Maximchuk** [comment]
Thank you for your wide answer!
