### ISSUE TITLE
Register a new account

### ISSUE THREAD

**Issue by Serg-Maximchuk** [Heat-Ledger-Ltd/heatledger#7]
Hello! I wonder how can I register new account in mainnet using [API](https://heatwallet.com/api/#!/Register/add). All these parameters, what are their validity conditions?  Because right now I receive 

```
curl -X GET --header 'Accept: application/json' 'https://heatwallet.com:7734/api/v1/register/now/test/test/test/true/test'
```
> {"errorDescription":"Incorrect \"publicKey\"","errorCode":2}

Even with generated mnemonic phrase:
```
curl -X GET --header 'Accept: application/json' 'https://heatwallet.com:7734/api/v1/register/now/fiscal%20accuse%20carbon%20arrow%20ranch%20sand%20piano%20battle%20rail%20buffalo%20excha
nge%20park/test/test/true/test'
``` 
I receive the same response.
What is the rules for mnemonic phrase? And where do I get the captcha value?

**Comment by dmdeklerk** [comment]
Hi, 

> Hello! I wonder how can I register new account in mainnet using API

short answer: you cant. As verified email ids are given out only by the HEAT organization.

> All these parameters, what are their validity conditions? Because right now I receive

They are not to be used by outsiders.

If I might offer a suggestion (if thats what you want to do) if all you want is to create a public key and numeric ID from a given private key.

Please consider using our NodeJS based SDK. Which is found here: https://www.npmjs.com/package/heat-sdk 

If this is the case let me know and I'll get you instructions on how to do that from a basic command line script. 

In case you dont want to use a client side script but prefer to use an REST API approach thats possible as well this one could be of help https://heatwallet.com/api/#!/Accounts/secretPhrase

**Comment by dmdeklerk** [comment]
Please have a look at these two as well.

https://heatwallet.com/api/#!/Tools/publickey
https://heatwallet.com/api/#!/Tools/id

**WARNING!!! It goes without saying of course to never expose your private key to any service online.**

**Comment by Serg-Maximchuk** [comment]
Thank you, I appreciate your answer!
