### ISSUE TITLE
Transaction's message decryption

### ISSUE THREAD

**Issue by Serg-Maximchuk** [Heat-Ledger-Ltd/heatledger#8]
Hello!
If I have a transaction with `"messageIsEncrypted": true`, how can I decrypt it's `messageBytes`?

**Comment by Serg-Maximchuk** [comment]
Oh as I can see [here ](https://github.com/heatcrypto/heat-sdk/blob/master/src/transaction.ts#L120), it's done with sender's secret phrase. I can't decrypt it without the phrase, can I?

**Comment by fitcoin** [comment]
That's right. It's why you need to run your own node to be able to decrypt securely and not transmit the secret phrase over the internet.

**Comment by Serg-Maximchuk** [comment]
Thanks!

**Comment by fitcoin** [comment]
If user sends you encrypted message, you can decrypt it with your private key (secret phrase). You don't need to know the sender's phrase.

**Comment by fitcoin** [comment]
Decrypt messageBytes with http://localhost:7733/api/v1/tools/aes/decryptMessageBytes/$messagebytes/$yourprivatekey/$senderpublickey

Get sender public key with https://heatwallet.com/api/#!/Accounts/payments

**Comment by Serg-Maximchuk** [comment]
Oh, great! So I can decrypt messages now, thank you! - this time for sure
